version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb-service
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  service-app:
    image: zenseit/app-service
    container_name: service
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - mongodb
    restart: on-failure
    networks:
      - mynetwork

  storage-app:
    image: zenseit/app-storage
    container_name: storage
    ports:
      - '8081:8081'
    depends_on:
      - mysql
      - rabbitmq
    restart: on-failure
    networks:
      - mynetwork

  socket-app:
    image: zenseit/app-socket
    container_name: socket
    ports:
      - '8082:8082'
    depends_on:
      - mysql
      - rabbitmq
    restart: on-failure
    networks:
      - mynetwork

  auth-app:
    image: zenseit/app-auth
    container_name: auth
    ports:
      - '8083:8083'
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - mynetwork

  front-app:
    image: zenseit/inventory-front
    container_name: front
    ports:
      - '4200:4200'
    restart: on-failure
    networks:
      - mynetwork


networks:
  mynetwork: