server:
  port: 8083
  error:
    include-message: always
spring:
  application:
    name: "inventoryProject"
  devtools:
    add-properties: false
  r2dbc:
    url: "${R2DBC_URI:r2dbc:mysql://mysql-service:3306/inventory}"
    username: root
    password: root
  data:
    mongodb:
      uri: "${MONGO_URI:mongodb://mongodb-service:27017/inventoryDB}"
  rabbitmq:
    host: "${RABBIT_URI:rabbitmq-service:5672}"
    username: "guest"
    password: "guest"
    virtual-host: "/"
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://inventory-front:4200"

springdoc:
  swagger-ui:
    path: /api/v1/inventory/swagger-ui.html

