server:
  port: 8082
  error:
    include-message: always
spring:
  application:
    name: "inventoryProject"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:mysql://database:3306/inventory
    username: root
    password: root
  data:
    mongodb:
      uri: "mongodb://mongodb:27017/inventoryDB"
  rabbitmq:
    host: "rabbitmq"
    username: "guest"
    password: "guest"
    virtual-host: "/"
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://inventory-front:4200"
